{% set name = "AmberTools" %}
# Versioning scheme uses AmberTools major release as MAJOR version number, patch level as MINOR version number
# Update the MINOR version number as new patch releases come out
{% set version = "19.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ambermd.org/downloads/AmberTools19.tar.bz2
  sha256: 0c86937904854b64e4831e047851f504ec45b42e593db4ded92c1bee5973e699
  # patches:
    # - patches/configure.patch
    # - patches/fix_memembed_includes.patch
    # - patches/do_not_build_boost.patch
    # - patches/enable_cmake.patch

build:
  number: 1
  skip: True  # [win or osx or py2k]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bc
    - flex
    - patch
    - tcsh
    - bison
    - make
    - cmake
    - perl
  host:
    - python
    - setuptools
    - cython
    - numpy
    - scipy
    - matplotlib
    - bzip2
    - zlib
    - boost-cpp
    - libnetcdf
    - netcdf-fortran
    - pthread-stubs
    - openmpi
    - openmp
    - fftw
    - liblapack
    - xorg-libxt
    - xorg-libxext
    - xorg-libx11
    - readline
    - llvm-openmp  # [osx]
  run:
    - python
    - cython
    - numpy
    - scipy
    - matplotlib
    - boost-cpp
    - libnetcdf
    - netcdf-fortran
    - fftw
    - libblas
    - liblapack
    - libopenblas
    - xorg-libxt
    - xorg-libxext
    - xorg-libx11
    - readline

test:
  commands:
    - antechamber -h
    - cpptraj -h
    - ffgbsa -h
    - MCPB.py -h
    - mdnab -h
    - minab -h
    - mmpbsa_py_energy -h
    - parmchk2 -h
    - parmed -h
    - pdb4amber -h
    - respgen -h
    - sqm -h
    - teLeap -h
    - tleap -h
  imports:
    - pytraj
    - parmed

about:
  home: http://ambermd.org/AmberTools.php
  license: Multiple
  license_file: AmberTools/LICENSE
  summary: 'AmberTools is a set of programs for biomolecular simulation and analysis'
  description: |
    AmberTools is a set of programs for biomolecular simulation and analysis.
    They are designed to work well with each other, and with the “regular” Amber
    suite of programs. You can perform many simulation tasks with AmberTools,
    and you can do more extensive simulations with the combination of AmberTools
    and Amber itself.

extra:
  recipe-maintainers:
    - simonbray
    - jaimergp
