{% set name = "AmberTools" %}
# Versioning scheme uses AmberTools major release as MAJOR version number, patch level as MINOR version number
# Update the MINOR version number as new patch releases come out
{% set version = "20.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ambermd.org/downloads/AmberTools20jlmrcc.tar.bz2
  sha256: b1e1f8f277c54e88abc9f590e788bbb2f7a49bcff5e8d8a6eacfaf332a4890f9
  patches:
    - patches/do_not_symlink_missing_ff12pol.patch

build:
  number: 0
  skip: True  # [win or py2k]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bc
    - flex
    - patch
    - tcsh
    - bison
    - make
    - cmake
    - perl
    - llvm-openmp  # [osx]
    - libgomp      # [linux and not aarch64]
  host:
    - python
    - setuptools
    - cython
    - numpy
    - scipy
    - matplotlib-base
    - bzip2
    - zlib
    - boost-cpp
    - libnetcdf
    - netcdf-fortran
    - pthread-stubs
    - fftw
    - arpack
    - libblas
    - liblapack
    - xorg-libxt  # [unix]
    - xorg-libxext   # [unix]
    - xorg-libx11   # [unix]
    - readline
    - llvm-openmp  # [osx]
    - libgomp      # [linux and not aarch64]
  run:
    - python
    - perl
    - cython
    - numpy
    - scipy
    - matplotlib-base
    - boost-cpp
    - libnetcdf
    - netcdf-fortran
    - fftw
    - libblas
    - liblapack
    - xorg-libxt  # [unix]
    - xorg-libxext  # [unix]
    - xorg-libx11   # [unix]
    - readline
    - llvm-openmp  # [osx]
    - libgomp      # [linux and not aarch64]
  run_constrained:
    - ambermini ==9999999999

test:
  requires:
{% if unit_tests == "run" %}
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - util-linux  # [linux64]
{% endif %}
    - tcsh
    # Try to force a library incompatibility error in osx (see #22)
    - lxml  # [osx]
    - rdkit  # [osx]
  source_files:
{% if unit_tests == "run" %}
    - "*"
{% else %}
    # we need to copy at least one file, otherwise we can't use SRC_DIR in run_test.sh
    - README
{% endif %}
  # commands: check run_test.sh for CLI tests
  imports:
    - parmed
    - pdb4amber
    - pymsmt
    - pytraj
    - sander
    # Try to force a library incompatibility error in osx (see #22)
    - rdkit  # [osx]
    - rdkit.Chem.AllChem  # [osx]

about:
  home: http://ambermd.org/AmberTools.php
  license: Multiple
  license_file: AmberTools/LICENSE
  summary: 'AmberTools is a set of programs for biomolecular simulation and analysis'
  description: |
    AmberTools is a set of programs for biomolecular simulation and analysis.
    They are designed to work well with each other, and with the "regular" Amber
    suite of programs. You can perform many simulation tasks with AmberTools,
    and you can do more extensive simulations with the combination of AmberTools
    and Amber itself.

extra:
  recipe-maintainers:
    - simonbray
    - jaimergp
