azure:
  store_build_artifacts: true
  free_disk_space: true
build_platform:
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_ppc64le: azure
test: native_and_emulated
upload_on_branch: main
