travis:
  secure:
    BINSTAR_TOKEN: ZNIy6T7/kNes/ESO1cPEGmBCwFhbDQykZ3xMaQu2Fo9ELzDRD5YEnViGZFwLTKjq+LvfnzdXxTtJXJ1FiyrIJG0OBCFMvr8eLq+NhQHgpoRUh7Ow1lKcjeV64/rQRHeTkZXkHQQmhpbnKHt9xhwGLFNoMoYbtY/i94Z1X4z4FAeSndqWNM+9pdSQhgORhrvl+MntOv/6SEWr18zRsS5pKQpONztFTUF2vImkQuqTCyFlj8bpwbcWG+7UHgdLOzxGXEDEFrJEO4yIuGCJMB+dGmB521t9ZJcJAb7W0BV/zt+SY7Z/w2b+ND13DDDGRtfcIqLG/IJGAYJJcvnBBTwrdaAbcEh7Yo7M8/v2BT4bT2c8TflSCB1a8Y+bJ+wIXkm0F9EishfvmRY3QbCkfKSWQNXaMeKTWzK1fZeo70DXe2yyd36GGTNWqQ4HaP8CUfZgvIw0SbpA1ICFxtC6dtqmdiDb0FCIq3YV+gUQC8rYdpPdG6Vtx5ycJNFvDRWTc6KDPk7tZn+ZPq3BF1M7eCuSOMvP4KnTzFsx0Yg1O8eR/FGV7w2qE6nHxb1xvmwlmq7MUcsbxKeTV3rARNCd5SYnWdy3DZ+92Se9pATbP7vtSu7aEPZkjb1+NwLO6u5APIx3U/xhBFmPqb78aawS6RdiA41y05hWeMgsQh4eu5hRdLQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  linux_ppc64le: azure
conda_forge_output_validation: true
