provider:
  linux_ppc64le: azure
conda_forge_output_validation: true
azure:
  store_build_artifacts: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
upload_on_branch: main
build_platform:
  osx_arm64: osx_64
test: native_and_emulated
