# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      linux_64_cuda_compiler_version12.6mpimpichpython3.10.____cpython:
        CONFIG: linux_64_cuda_compiler_version12.6mpimpichpython3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_cuda_compiler_version12.6mpimpi_h8def309c
      linux_64_cuda_compiler_version12.6mpimpichpython3.11.____cpython:
        CONFIG: linux_64_cuda_compiler_version12.6mpimpichpython3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_cuda_compiler_version12.6mpimpi_hbdca9c9e
      linux_64_cuda_compiler_version12.6mpimpichpython3.12.____cpython:
        CONFIG: linux_64_cuda_compiler_version12.6mpimpichpython3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_cuda_compiler_version12.6mpimpi_hdf3e5526
      linux_64_cuda_compiler_version12.6mpimpichpython3.13.____cp313:
        CONFIG: linux_64_cuda_compiler_version12.6mpimpichpython3.13.____cp313
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_cuda_compiler_version12.6mpimpi_h5b48fb67
      linux_64_cuda_compiler_version12.6mpinompipython3.10.____cpython:
        CONFIG: linux_64_cuda_compiler_version12.6mpinompipython3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_cuda_compiler_version12.6mpinom_h6565e277
      linux_64_cuda_compiler_version12.6mpinompipython3.11.____cpython:
        CONFIG: linux_64_cuda_compiler_version12.6mpinompipython3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_cuda_compiler_version12.6mpinom_h60cae82a
      linux_64_cuda_compiler_version12.6mpinompipython3.12.____cpython:
        CONFIG: linux_64_cuda_compiler_version12.6mpinompipython3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_cuda_compiler_version12.6mpinom_haf383edd
      linux_64_cuda_compiler_version12.6mpinompipython3.13.____cp313:
        CONFIG: linux_64_cuda_compiler_version12.6mpinompipython3.13.____cp313
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_cuda_compiler_version12.6mpinom_h51ebcb92
      linux_64_cuda_compiler_version12.6mpiopenmpipython3.10.____cpython:
        CONFIG: linux_64_cuda_compiler_version12.6mpiopenmpipython3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_cuda_compiler_version12.6mpiope_hfaacdb43
      linux_64_cuda_compiler_version12.6mpiopenmpipython3.11.____cpython:
        CONFIG: linux_64_cuda_compiler_version12.6mpiopenmpipython3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_cuda_compiler_version12.6mpiope_he62e2186
      linux_64_cuda_compiler_version12.6mpiopenmpipython3.12.____cpython:
        CONFIG: linux_64_cuda_compiler_version12.6mpiopenmpipython3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_cuda_compiler_version12.6mpiope_h390d2610
      linux_64_cuda_compiler_version12.6mpiopenmpipython3.13.____cp313:
        CONFIG: linux_64_cuda_compiler_version12.6mpiopenmpipython3.13.____cp313
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_cuda_compiler_version12.6mpiope_hca4add00
      linux_64_cuda_compiler_versionNonempimpichpython3.10.____cpython:
        CONFIG: linux_64_cuda_compiler_versionNonempimpichpython3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_cuda_compiler_versionNonempimpi_h5b899012
      linux_64_cuda_compiler_versionNonempimpichpython3.11.____cpython:
        CONFIG: linux_64_cuda_compiler_versionNonempimpichpython3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_cuda_compiler_versionNonempimpi_h087eee4c
      linux_64_cuda_compiler_versionNonempimpichpython3.12.____cpython:
        CONFIG: linux_64_cuda_compiler_versionNonempimpichpython3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_cuda_compiler_versionNonempimpi_h4ecc2b7a
      linux_64_cuda_compiler_versionNonempimpichpython3.13.____cp313:
        CONFIG: linux_64_cuda_compiler_versionNonempimpichpython3.13.____cp313
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_cuda_compiler_versionNonempimpi_h847db604
      linux_64_cuda_compiler_versionNonempinompipython3.10.____cpython:
        CONFIG: linux_64_cuda_compiler_versionNonempinompipython3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_cuda_compiler_versionNonempinom_hd6eef30b
      linux_64_cuda_compiler_versionNonempinompipython3.11.____cpython:
        CONFIG: linux_64_cuda_compiler_versionNonempinompipython3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_cuda_compiler_versionNonempinom_hdcf9bd84
      linux_64_cuda_compiler_versionNonempinompipython3.12.____cpython:
        CONFIG: linux_64_cuda_compiler_versionNonempinompipython3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_cuda_compiler_versionNonempinom_h4bf460c8
      linux_64_cuda_compiler_versionNonempinompipython3.13.____cp313:
        CONFIG: linux_64_cuda_compiler_versionNonempinompipython3.13.____cp313
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_cuda_compiler_versionNonempinom_h6c9ae7b5
      linux_64_cuda_compiler_versionNonempiopenmpipython3.10.____cpython:
        CONFIG: linux_64_cuda_compiler_versionNonempiopenmpipython3.10.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_cuda_compiler_versionNonempiope_hbfe03820
      linux_64_cuda_compiler_versionNonempiopenmpipython3.11.____cpython:
        CONFIG: linux_64_cuda_compiler_versionNonempiopenmpipython3.11.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_cuda_compiler_versionNonempiope_h4db71303
      linux_64_cuda_compiler_versionNonempiopenmpipython3.12.____cpython:
        CONFIG: linux_64_cuda_compiler_versionNonempiopenmpipython3.12.____cpython
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_cuda_compiler_versionNonempiope_h290032ef
      linux_64_cuda_compiler_versionNonempiopenmpipython3.13.____cp313:
        CONFIG: linux_64_cuda_compiler_versionNonempiopenmpipython3.13.____cp313
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-x86_64:alma9
        SHORT_CONFIG: linux_64_cuda_compiler_versionNonempiope_hfbde7564
  timeoutInMinutes: 360
  variables: {}

  steps:
  - script: |
         sudo mkdir -p /opt/empty_dir || true
         for d in \
                  /opt/ghc \
                  /opt/hostedtoolcache \
                  /usr/lib/jvm \
                  /usr/local/.ghcup \
                  /usr/local/lib/android \
                  /usr/local/share/powershell \
                  /usr/share/dotnet \
                  /usr/share/swift \
                  ; do
           sudo rsync --stats -a --delete /opt/empty_dir/ $d || true
         done
         sudo apt-get purge -y -f firefox \
                                  google-chrome-stable \
                                  microsoft-edge-stable
         sudo apt-get autoremove -y >& /dev/null
         sudo apt-get autoclean -y >& /dev/null
         df -h
    displayName: Manage disk space
  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export flow_run_id=azure_$(Build.BuildNumber).$(System.JobAttempt)
        export remote_url=$(Build.Repository.Uri)
        export sha=$(Build.SourceVersion)
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        export UPLOAD_ON_BRANCH="main"
        if [[ "${BUILD_REASON:-}" == "PullRequest" ]]; then
          export IS_PR_BUILD="True"
        else
          export IS_PR_BUILD="False"
        fi
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
  - script: |
        export CI=azure
        export CI_RUN_ID=$(build.BuildNumber).$(system.JobAttempt)
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        export CONDA_BLD_DIR=build_artifacts
        export ARTIFACT_STAGING_DIR="$(Build.ArtifactStagingDirectory)"
        # Archive everything in CONDA_BLD_DIR except environments
        export BLD_ARTIFACT_PREFIX=conda_artifacts
        if [[ "$AGENT_JOBSTATUS" == "Failed" ]]; then
          # Archive the CONDA_BLD_DIR environments only when the job fails
          export ENV_ARTIFACT_PREFIX=conda_envs
        fi
        ./.scripts/create_conda_build_artifacts.sh
    displayName: Prepare conda build artifacts
    condition: succeededOrFailed()

  - task: PublishPipelineArtifact@1
    displayName: Store conda build artifacts
    condition: not(eq(variables.BLD_ARTIFACT_PATH, ''))
    inputs:
      targetPath: $(BLD_ARTIFACT_PATH)
      artifactName: $(BLD_ARTIFACT_NAME)

  - task: PublishPipelineArtifact@1
    displayName: Store conda build environment artifacts
    condition: not(eq(variables.ENV_ARTIFACT_PATH, ''))
    inputs:
      targetPath: $(ENV_ARTIFACT_PATH)
      artifactName: $(ENV_ARTIFACT_NAME)
